name: CI
on: [push, pull_request, workflow_dispatch]

env:
  FORCE_COLOR: true

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest

    steps:
      - name: Download
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'

      - name: Get Yarn cache directory
        id: yarn_cache_dir
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Set up caching
        uses: actions/cache@v2
        with:
          path: |
            ${{ steps.yarn_cache_dir.outputs.dir }}
          key: |
            r1/${{ github.workflow }}/${{ runner.os }}/yarn/${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            r1/${{ github.workflow }}/${{ runner.os }}/yarn/

      - run: yarn install --frozen-lockfile
      - run: yarn run lint
      - run: yarn run check-fmt
